version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - ps: ./gradlew.bat cleanTest test --info --stacktrace --no-daemon
  # TODO: come up with a better way to list tests that we want to run on appveyor
  - ps: ./gradlew.bat :digdag-test:test --info --stacktrace --no-daemon -Dtest.single=InitIT

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

install:
  - ps: Install-Product node '6.9.1'
  - npm install -g npm
  - node --version
  - npm --version
  - echo %PATH%
  - ps: echo $env:PATH

test: off
