version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat cleanTest test --info --no-daemon
  # TODO: come up with a better way to list tests that we want to run on appveyor
  - gradlew.bat :digdag-test:test --info --no-daemon -Dtest.single=InitIT
  - gradlew.bat :digdag-test:test --info --no-daemon -Dtest.single=RunIT

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

test: off
